import type { Constraint } from './types';

// Category strings (e.g. 'animal', 'residential') and specific object-library
// type ids (e.g. 'well', 'septic') can both be used as matchers — a single
// list drives both placement scoring (engine/placement.ts) and post-hoc
// warnings (engine/warnings.ts), per the "single source of truth" handoff note.
export const CONSTRAINTS: Constraint[] = [
  {
    id: 'well-septic-separation',
    kind: 'separation',
    subjectTypes: ['well'],
    relatedTypes: ['septic'],
    minDistance: 15,
    hard: true,
    severity: 'critical',
    message: 'Well is closer than the 15 m safe minimum separation from the septic system.',
  },
  {
    id: 'well-tank-water-quality',
    kind: 'separation',
    subjectTypes: ['well'],
    relatedTypes: ['compost'],
    minDistance: 10,
    hard: false,
    severity: 'caution',
    message: 'Well is close to the compost yard; runoff could affect water quality.',
  },
  {
    id: 'animal-residential-separation',
    kind: 'separation',
    subjectTypes: ['animal'],
    relatedTypes: ['residential'],
    minDistance: 10,
    hard: false,
    severity: 'caution',
    message: 'Animal zone is close to the house; expect noise and odor at this distance.',
  },
  {
    id: 'animal-leisure-separation',
    kind: 'separation',
    subjectTypes: ['animal'],
    relatedTypes: ['leisure'],
    minDistance: 12,
    hard: false,
    severity: 'caution',
    message: 'Animal zone is close to a leisure area; odor may reduce comfort there.',
  },
  {
    id: 'compost-residential-separation',
    kind: 'separation',
    subjectTypes: ['compost'],
    relatedTypes: ['residential'],
    minDistance: 6,
    hard: false,
    severity: 'info',
    message: 'Compost yard is close to the house.',
  },
  {
    id: 'compost-leisure-separation',
    kind: 'separation',
    subjectTypes: ['compost'],
    relatedTypes: ['leisure'],
    minDistance: 8,
    hard: false,
    severity: 'caution',
    message: 'Compost yard is close to a leisure area; odor may be noticeable.',
  },
  {
    id: 'generator-noise-separation',
    kind: 'separation',
    subjectTypes: ['generator'],
    relatedTypes: ['residential', 'leisure'],
    minDistance: 8,
    hard: false,
    severity: 'caution',
    message: 'Backup generator is close to a quiet zone; expect noise when running.',
  },
  {
    id: 'kitchen-garden-adjacency',
    kind: 'adjacency',
    subjectTypes: ['raised-beds'],
    relatedTypes: ['residential'],
    maxDistance: 20,
    hard: false,
    severity: 'info',
    message: 'Kitchen garden is far from the house, adding daily walking distance.',
  },
  {
    id: 'greenhouse-utility-adjacency',
    kind: 'adjacency',
    subjectTypes: ['greenhouse', 'hydroponic-tower'],
    relatedTypes: ['water', 'energy'],
    maxDistance: 30,
    hard: false,
    severity: 'info',
    message: 'Greenhouse is far from water/power utilities, complicating irrigation and heating runs.',
  },
  {
    id: 'solar-battery-adjacency',
    kind: 'adjacency',
    subjectTypes: ['solar-array'],
    relatedTypes: ['battery-room'],
    maxDistance: 12,
    hard: false,
    severity: 'caution',
    message: 'Solar array is far from the battery room, increasing cable losses and cost.',
  },
  {
    id: 'well-pump-adjacency',
    kind: 'adjacency',
    subjectTypes: ['well'],
    relatedTypes: ['pump'],
    maxDistance: 8,
    hard: false,
    severity: 'caution',
    message: 'Well is far from the pump house.',
  },
  {
    id: 'pump-tank-adjacency',
    kind: 'adjacency',
    subjectTypes: ['pump'],
    relatedTypes: ['water-tank'],
    maxDistance: 10,
    hard: false,
    severity: 'info',
    message: 'Pump is far from the water tank.',
  },
];
