import type { Constraint, WarningSeverity } from './types';

// Category strings (e.g. 'animal', 'residential') and specific object-library
// type ids (e.g. 'well', 'septic') can both be used as matchers — a single
// list drives both placement scoring (engine/placement.ts) and post-hoc
// warnings (engine/warnings.ts), per the "single source of truth" handoff note.
export const CONSTRAINTS: Constraint[] = [
  {
    id: 'well-septic-separation',
    kind: 'separation',
    subjectTypes: ['well'],
    relatedTypes: ['septic'],
    minDistance: 15,
    hard: true,
    severity: 'critical',
    message: 'Well is closer than the 15 m safe minimum separation from the septic system.',
  },
  {
    id: 'well-tank-water-quality',
    kind: 'separation',
    subjectTypes: ['well'],
    relatedTypes: ['compost'],
    minDistance: 10,
    hard: false,
    severity: 'caution',
    message: 'Well is close to the compost yard; runoff could affect water quality.',
  },
  {
    id: 'animal-residential-separation',
    kind: 'separation',
    subjectTypes: ['animal'],
    relatedTypes: ['residential'],
    minDistance: 10,
    hard: false,
    severity: 'caution',
    message: 'Animal zone is close to the house; expect noise and odor at this distance.',
  },
  {
    id: 'animal-leisure-separation',
    kind: 'separation',
    subjectTypes: ['animal'],
    relatedTypes: ['leisure'],
    minDistance: 12,
    hard: false,
    severity: 'caution',
    message: 'Animal zone is close to a leisure area; odor may reduce comfort there.',
  },
  {
    id: 'compost-residential-separation',
    kind: 'separation',
    subjectTypes: ['compost'],
    relatedTypes: ['residential'],
    minDistance: 6,
    hard: false,
    severity: 'info',
    message: 'Compost yard is close to the house.',
  },
  {
    id: 'compost-leisure-separation',
    kind: 'separation',
    subjectTypes: ['compost'],
    relatedTypes: ['leisure'],
    minDistance: 8,
    hard: false,
    severity: 'caution',
    message: 'Compost yard is close to a leisure area; odor may be noticeable.',
  },
  {
    id: 'generator-noise-separation',
    kind: 'separation',
    subjectTypes: ['generator'],
    relatedTypes: ['residential', 'leisure'],
    minDistance: 8,
    hard: false,
    severity: 'caution',
    message: 'Backup generator is close to a quiet zone; expect noise when running.',
  },
  {
    id: 'kitchen-garden-adjacency',
    kind: 'adjacency',
    subjectTypes: ['raised-beds'],
    relatedTypes: ['residential'],
    maxDistance: 20,
    hard: false,
    severity: 'info',
    message: 'Kitchen garden is far from the house, adding daily walking distance.',
  },
  {
    id: 'greenhouse-utility-adjacency',
    kind: 'adjacency',
    subjectTypes: ['greenhouse', 'hydroponic-tower'],
    relatedTypes: ['water', 'energy'],
    maxDistance: 30,
    hard: false,
    severity: 'info',
    message: 'Greenhouse is far from water/power utilities, complicating irrigation and heating runs.',
  },
  {
    id: 'solar-battery-adjacency',
    kind: 'adjacency',
    subjectTypes: ['solar-array'],
    relatedTypes: ['battery-room'],
    maxDistance: 12,
    hard: false,
    severity: 'caution',
    message: 'Solar array is far from the battery room, increasing cable losses and cost.',
  },
  {
    id: 'well-pump-adjacency',
    kind: 'adjacency',
    subjectTypes: ['well'],
    relatedTypes: ['pump'],
    maxDistance: 8,
    hard: false,
    severity: 'caution',
    message: 'Well is far from the pump house.',
  },
  {
    id: 'pump-tank-adjacency',
    kind: 'adjacency',
    subjectTypes: ['pump'],
    relatedTypes: ['water-tank'],
    maxDistance: 10,
    hard: false,
    severity: 'info',
    message: 'Pump is far from the water tank.',
  },
  // Fire-safety separations. Distances follow common practice for
  // wood-frame outbuilding spacing (roughly 6-15 m depending on
  // construction material); treated as guidance (soft), not a hard
  // placement filter, since exact local building code varies by region.
  {
    id: 'fire-house-outbuilding-separation',
    kind: 'safety',
    subjectTypes: ['house', 'house-l'],
    relatedTypes: ['barn', 'shed', 'woodshed', 'goat-shelter', 'poultry-coop', 'banya', 'smokehouse'],
    minDistance: 8,
    hard: false,
    severity: 'caution',
    message: 'Fire-safety guidance recommends greater separation between the house and combustible outbuildings (typically 8-15 m depending on materials).',
  },
  {
    id: 'fire-outbuilding-mutual-separation',
    kind: 'safety',
    subjectTypes: ['barn', 'shed', 'woodshed', 'goat-shelter', 'poultry-coop', 'banya', 'smokehouse'],
    relatedTypes: ['barn', 'shed', 'woodshed', 'goat-shelter', 'poultry-coop', 'banya', 'smokehouse'],
    minDistance: 6,
    hard: false,
    severity: 'info',
    message: 'Fire-safety guidance recommends at least 6 m between combustible outbuildings.',
  },
  {
    id: 'banya-woodshed-clearance',
    kind: 'safety',
    subjectTypes: ['banya', 'smokehouse'],
    relatedTypes: ['woodshed'],
    minDistance: 5,
    hard: false,
    severity: 'caution',
    message: 'A wood-fired firebox this close to stored firewood is a fire risk.',
  },
  {
    id: 'apiary-people-separation',
    kind: 'safety',
    subjectTypes: ['apiary'],
    relatedTypes: ['leisure', 'residential'],
    minDistance: 8,
    hard: false,
    severity: 'caution',
    message: 'Beehives this close to a house entrance or leisure area risk stings from foraging bees crossing paths with people.',
  },
  {
    id: 'generator-electrical-fire-clearance',
    kind: 'safety',
    subjectTypes: ['generator'],
    relatedTypes: ['house', 'house-l', 'barn', 'shed', 'woodshed'],
    minDistance: 3,
    hard: true,
    severity: 'critical',
    message: 'Fuel-fired generators need at least 3 m clearance from combustible structures — exhaust heat and fuel are a fire/electrical hazard at this distance.',
  },
  {
    id: 'generator-woodshed-clearance',
    kind: 'safety',
    subjectTypes: ['generator'],
    relatedTypes: ['woodshed'],
    minDistance: 5,
    hard: false,
    severity: 'caution',
    message: 'Stored firewood this close to a fuel-fired generator is a fire risk.',
  },
  {
    id: 'battery-woodshed-clearance',
    kind: 'safety',
    subjectTypes: ['battery-room'],
    relatedTypes: ['woodshed'],
    minDistance: 2,
    hard: false,
    severity: 'caution',
    message: 'Battery storage next to firewood is a fire risk; keep some clearance.',
  },
  {
    id: 'pool-electrical-clearance',
    kind: 'safety',
    subjectTypes: ['pool'],
    relatedTypes: ['solar-array', 'battery-room', 'inverter-room', 'generator'],
    minDistance: 3,
    hard: false,
    severity: 'caution',
    message: 'Electrical safety codes require clearance between pools and mains-connected electrical equipment.',
  },
  {
    id: 'cistern-house-adjacency',
    kind: 'adjacency',
    subjectTypes: ['rainwater-cistern'],
    relatedTypes: ['residential'],
    maxDistance: 10,
    hard: false,
    severity: 'info',
    message: 'Rainwater cistern is far from the house, requiring a longer downspout/gutter run.',
  },
  {
    id: 'hydro-battery-adjacency',
    kind: 'adjacency',
    subjectTypes: ['micro-hydro'],
    relatedTypes: ['battery-room'],
    maxDistance: 15,
    hard: false,
    severity: 'caution',
    message: 'Micro-hydro turbine is far from the battery room, increasing cable losses and cost.',
  },
];

export interface BoundarySetback {
  id: string;
  appliesTo: string[]; // typeIds or categories
  minDistanceM: number;
  severity: WarningSeverity;
  message: string;
}

// Property-line setbacks. These mirror common dacha/allotment building-code
// practice (house ≥3 m from the boundary, outbuildings/animal housing ≥4 m,
// wells kept apart from the boundary for a sanitary margin, etc.) — offered
// as planning guidance, not a substitute for the actual local building code.
export const BOUNDARY_SETBACKS: BoundarySetback[] = [
  {
    id: 'setback-house',
    appliesTo: ['house', 'house-l'],
    minDistanceM: 3,
    severity: 'caution',
    message: 'is closer than the typical 3 m property-line setback for a dwelling.',
  },
  {
    id: 'setback-outbuilding',
    appliesTo: ['storage', 'animal', 'banya'],
    minDistanceM: 4,
    severity: 'caution',
    message: 'is closer than the typical 4 m setback for outbuildings/animal housing from the neighboring boundary.',
  },
  {
    id: 'setback-perennial',
    appliesTo: ['food-perennial'],
    minDistanceM: 2,
    severity: 'info',
    message: 'is close enough to the boundary that mature trees/vines may overhang neighboring land.',
  },
  {
    id: 'setback-well',
    appliesTo: ['well'],
    minDistanceM: 5,
    severity: 'caution',
    message: 'is closer than the typical 5 m sanitary setback for a well from the property line.',
  },
  {
    id: 'setback-septic',
    appliesTo: ['septic'],
    minDistanceM: 2,
    severity: 'caution',
    message: 'is closer than the typical 2 m setback for a septic system from the property line.',
  },
  {
    id: 'setback-pool',
    appliesTo: ['pool'],
    minDistanceM: 2,
    severity: 'info',
    message: 'is close to the boundary — keep clearance for maintenance access and safety.',
  },
];
