//  Generated by scripts/build_model_metrics.py — do not edit by hand.
//
//  The bounding box of every vendored mesh, in its own model units, measured
//  from the OBJ files. See the script for why this is generated rather than
//  read at runtime: the scene builder needs real sizes on a platform that
//  cannot open a mesh, let alone render one.
//
//  Axes are the meshes' own — Kenney models are Y-up, like SceneKit. The
//  engine is Z-up, and `SceneNode` is where the two are reconciled, once.

import Foundation

/// How big one mesh is, and where it sits relative to its own origin.
public struct ModelBounds: Equatable, Sendable {
    public let minX: Double, maxX: Double
    public let minY: Double, maxY: Double
    public let minZ: Double, maxZ: Double

    public init(minX: Double, maxX: Double, minY: Double, maxY: Double, minZ: Double, maxZ: Double) {
        self.minX = minX; self.maxX = maxX
        self.minY = minY; self.maxY = maxY
        self.minZ = minZ; self.maxZ = maxZ
    }

    /// Extent along each of the mesh's own axes.
    public var width: Double { maxX - minX }
    public var height: Double { maxY - minY }
    public var depth: Double { maxZ - minZ }

    /// The largest horizontal extent — what a mesh is "about" that big.
    public var span: Double { max(width, depth) }

    /// The centre of the box, which is rarely the origin.
    public var centreX: Double { (minX + maxX) / 2 }
    public var centreZ: Double { (minZ + maxZ) / 2 }

    /// How far the mesh's own origin sits above its lowest point. Most of
    /// these kits model with the origin on the ground, but not all of them,
    /// and one that does not will float or sink.
    public var baseOffset: Double { -minY }
}

public enum ModelMetrics {
    /// Every vendored mesh, by `kit/name`.
    public static let all: [String: ModelBounds] = parse(table)

    public static subscript(_ name: String) -> ModelBounds? { all[name] }

    public static var names: [String] { all.keys.sorted() }

    /// One line per mesh: `name minX maxX minY maxY minZ maxZ`.
    ///
    /// A string rather than a dictionary literal on purpose. Swift type-checks
    /// a 380-entry literal of six-field structs slowly enough to notice, and
    /// this parses in microseconds, once.
    private static func parse(_ table: String) -> [String: ModelBounds] {
        var result: [String: ModelBounds] = [:]
        result.reserveCapacity(400)
        for line in table.split(separator: "\n") {
            let field = line.split(separator: " ")
            guard field.count == 7, let minX = Double(field[1]), let maxX = Double(field[2]),
                  let minY = Double(field[3]), let maxY = Double(field[4]),
                  let minZ = Double(field[5]), let maxZ = Double(field[6]) else { continue }
            result[String(field[0])] = ModelBounds(
                minX: minX, maxX: maxX, minY: minY, maxY: maxY, minZ: minZ, maxZ: maxZ
            )
        }
        return result
    }

    private static let table = """
city/building-type-a -0.6500 0.6500 0.0000 0.8335 -0.5141 0.5141
city/building-type-b -0.9140 0.9140 0.0000 1.1375 -0.5700 0.5700
city/building-type-c -0.6432 0.6432 0.0000 1.0335 -0.5141 0.5141
city/building-type-d -0.8782 0.8782 0.0000 1.2375 -0.5140 0.5140
city/building-type-e -0.6500 0.6500 0.0000 1.1375 -0.5140 0.5140
city/building-type-f -0.7140 0.7140 0.0000 1.1375 -0.7029 0.7029
city/building-type-g -0.7250 0.7250 0.0000 0.7682 -0.5890 0.5890
city/building-type-h -0.6500 0.6500 0.0000 0.7375 -0.4580 0.4580
city/building-type-i -0.6432 0.6432 0.0000 0.7375 -0.5140 0.5140
city/building-type-j -0.6850 0.6850 0.0000 1.0375 -0.4580 0.4580
city/building-type-k -0.4605 0.4605 0.0000 1.1496 -0.5100 0.5100
city/building-type-l -0.5168 0.5168 0.0000 1.0492 -0.5100 0.5100
city/building-type-m -0.7140 0.7140 0.0000 0.7375 -0.7140 0.7140
city/building-type-n -0.8921 0.8921 0.0000 1.1375 -0.6889 0.6889
city/building-type-o -0.6350 0.6350 0.0000 1.1375 -0.5140 0.5140
city/building-type-p -0.6200 0.6200 0.0000 0.9180 -0.4950 0.4950
city/building-type-q -0.6200 0.6200 -0.0000 0.9180 -0.4220 0.4636
city/building-type-r -0.5140 0.5140 0.0000 1.1411 -0.5100 0.5100
city/building-type-s -0.7030 0.7030 0.0000 1.1375 -0.5432 0.5432
city/building-type-t -0.6636 0.6500 0.0000 1.1563 -0.7032 0.7032
city/building-type-u -0.7140 0.7140 0.0000 1.1375 -0.5435 0.5435
city/driveway-long -0.1800 0.1800 0.0000 0.0100 -0.2000 0.2000
city/driveway-short -0.1800 0.1800 0.0000 0.0100 -0.1000 0.1000
city/fence-1x2 -0.4375 0.4375 -0.0000 0.2700 -0.2000 0.2375
city/fence-1x3 -0.6375 0.6375 -0.0000 0.2700 -0.2000 0.2375
city/fence-1x4 -0.8375 0.8375 -0.0000 0.2700 -0.2000 0.2375
city/fence-2x2 -0.4375 0.4375 -0.0000 0.2700 -0.4000 0.4375
city/fence-2x3 -0.6375 0.6375 -0.0000 0.2700 -0.4000 0.4375
city/fence-3x2 -0.4375 0.4375 -0.0000 0.2700 -0.6000 0.6375
city/fence-3x3 -0.6375 0.6375 -0.0000 0.2700 -0.6000 0.6375
city/fence-low -0.6375 0.6375 0.0000 0.1700 -0.4375 0.4000
city/fence -0.2375 0.2375 0.0000 0.2700 -0.0375 0.0375
city/path-long -0.1000 0.1000 0.0000 0.0100 -0.2000 0.2000
city/path-short -0.1000 0.1000 0.0000 0.0100 -0.1000 0.1000
city/path-stones-long -0.0700 0.0700 0.0000 0.0100 -0.2000 0.2000
city/path-stones-messy -0.0778 0.0778 0.0000 0.0100 -0.1807 0.1807
city/path-stones-short -0.0700 0.0700 0.0000 0.0100 -0.1000 0.1000
city/planter -0.2000 0.2000 0.0000 0.1771 -0.1506 0.1494
city/tree-large -0.1052 0.1052 0.0000 0.7670 -0.1215 0.1215
city/tree-small -0.1052 0.1052 0.0000 0.5670 -0.1215 0.1215
forest/bridge -0.5205 0.5205 -0.0000 0.4729 -0.4011 0.4000
forest/building-platform -0.6500 0.6500 0.0000 0.5000 -0.6500 0.6500
forest/building-roof -0.6704 0.6704 0.0000 1.0500 -0.5827 0.5827
forest/building-structure -0.5000 0.5000 0.0000 1.0000 -0.5000 0.5000
forest/character-archer -0.3903 0.3903 0.0000 0.8210 -0.2224 0.2476
forest/fence -0.5479 0.5479 -0.0000 0.4000 -0.1229 0.1229
forest/flag -0.0782 0.3541 -0.0000 0.7500 -0.0782 0.0782
forest/ladder -0.2524 0.2524 0.0000 1.0000 -0.0500 0.0875
forest/patch-dirt -0.5000 0.5000 0.0000 0.1000 -0.5000 0.5000
forest/patch-grass -0.5000 0.5000 0.0000 0.1710 -0.5000 0.5000
forest/plant -0.1478 0.2485 -0.0170 0.1749 -0.2152 0.2152
forest/platform -0.5000 0.5000 0.0000 0.4696 -0.5000 0.5000
forest/rocks-high -0.5000 0.5000 -0.5000 0.5000 -0.5000 0.5000
forest/rocks-low -0.5000 0.5000 0.0000 0.5228 -0.5000 0.5000
forest/rocks-ramp -0.5000 0.5000 0.0000 0.5000 -0.5000 0.5000
forest/stones -0.4546 0.4494 0.0000 0.4539 -0.4023 0.4499
forest/target -0.2750 0.2750 -0.0000 0.5806 -0.2840 0.1871
forest/tent -0.6310 0.6310 -0.0000 1.0000 -0.5374 0.5374
forest/tree-high -0.4637 0.4637 -0.0000 2.2839 -0.4414 0.4414
forest/tree -0.4637 0.4637 -0.0000 1.6839 -0.4414 0.4414
forest/weapon-arrow -0.0595 0.0595 -0.0595 0.0595 -0.2280 0.2280
forest/weapon-bow -0.0979 0.0211 0.0000 0.4787 0.0000 0.2089
survival/barrel-open -0.1182 0.1182 0.0000 0.3440 -0.1182 0.1182
survival/barrel -0.1182 0.1182 0.0000 0.3440 -0.1182 0.1182
survival/bedroll-frame -0.1361 0.1361 0.0000 0.1477 -0.3038 0.3038
survival/bedroll-packed -0.1302 0.1302 0.0000 0.0897 -0.0448 0.0448
survival/bedroll -0.1552 0.1552 -0.0500 0.0748 -0.3038 0.3038
survival/bottle-large -0.0362 0.0362 0.0000 0.1439 -0.0418 0.0418
survival/bottle -0.0263 0.0263 0.0000 0.1539 -0.0304 0.0304
survival/box-large-open -0.1250 0.1250 0.0000 0.3063 -0.2500 0.2500
survival/box-large -0.1250 0.1250 0.0000 0.2500 -0.2500 0.2500
survival/box-open -0.1250 0.1250 0.0000 0.3063 -0.1250 0.1250
survival/box -0.1250 0.1250 0.0000 0.2500 -0.1250 0.1250
survival/bucket -0.0721 0.0721 0.0000 0.1921 -0.0721 0.0721
survival/campfire-fishing-stand -0.1973 0.1973 0.0000 0.2760 -0.1266 0.1266
survival/campfire-pit -0.1389 0.1389 0.0000 0.1091 -0.1346 0.1346
survival/campfire-stand -0.2050 0.2050 0.0000 0.2810 -0.0622 0.0622
survival/chest -0.1302 0.1302 0.0000 0.2572 -0.1418 0.1302
survival/fence-doorway -0.2500 0.2500 0.0000 0.5175 -0.2527 -0.2046
survival/fence-fortified -0.2500 0.2500 0.0000 0.5175 -0.2500 -0.1970
survival/fence -0.2500 0.2500 0.0000 0.5175 -0.2500 -0.2072
survival/fish-large -0.1536 0.1536 -0.0000 0.1595 -0.0490 0.0490
survival/fish -0.1024 0.1024 0.0000 0.1063 -0.0326 0.0326
survival/floor-hole -0.2554 0.2447 0.0000 0.0668 -0.2467 0.2533
survival/floor-old -0.2554 0.2447 0.0000 0.0512 -0.2467 0.2533
survival/floor -0.2554 0.2447 0.0000 0.0512 -0.2467 0.2533
survival/grass-large -0.2379 0.2379 0.0000 0.1425 -0.2437 0.2437
survival/grass -0.1172 0.1172 0.0000 0.1425 -0.1286 0.1286
survival/metal-panel-narrow -0.1250 0.1250 0.0000 0.5000 -0.0250 0.0250
survival/metal-panel-screws-half -0.2500 0.2500 0.0000 0.2500 -0.0250 0.0375
survival/metal-panel-screws-narrow -0.1250 0.1250 0.0000 0.5000 -0.0250 0.0375
survival/metal-panel-screws -0.2500 0.2500 0.0000 0.5000 -0.0250 0.0375
survival/metal-panel -0.2500 0.2500 0.0000 0.5000 -0.0250 0.0250
survival/patch-grass-large -0.7000 0.7000 0.0000 0.0000 -0.6000 0.6000
survival/patch-grass -0.6000 0.6000 0.0000 0.0000 -0.6000 0.6000
survival/resource-planks -0.1865 0.1865 0.0000 0.0936 -0.3130 0.3130
survival/resource-stone-large -0.1880 0.1880 0.0000 0.1602 -0.1685 0.1685
survival/resource-stone -0.0827 0.0827 0.0000 0.1068 -0.0711 0.0711
survival/resource-wood -0.1025 0.1025 0.0000 0.0624 -0.0435 0.0435
survival/rock-a -0.3000 0.2552 0.0000 0.3927 -0.2971 0.3245
survival/rock-b -0.3784 0.4563 -0.0000 0.4186 -0.3549 0.3698
survival/rock-c -0.3813 0.4024 0.0000 0.5100 -0.2893 0.2766
survival/rock-flat-grass -0.8964 0.8900 0.0000 0.2258 -0.7400 0.7078
survival/rock-flat -0.8964 0.8900 0.0000 0.1950 -0.7400 0.7078
survival/rock-sand-a -0.3000 0.2552 0.0000 0.3927 -0.1907 0.2938
survival/rock-sand-b -0.3784 0.4207 0.0000 0.4486 -0.3640 0.4255
survival/rock-sand-c -0.3813 0.4024 -0.0000 0.5100 -0.3070 0.2621
survival/signpost-single -0.1123 0.0964 0.0000 0.4601 -0.0180 0.0250
survival/signpost -0.1123 0.1018 0.0000 0.4601 -0.0180 0.0250
survival/structure-canvas -0.2500 0.2500 0.0000 0.5000 -0.2500 0.2500
survival/structure-floor -0.2500 0.2500 0.0000 0.5487 -0.2500 0.2500
survival/structure-metal-doorway -0.2677 0.2677 -0.0000 0.5175 -0.2677 -0.1788
survival/structure-metal-floor -0.2500 0.2500 -0.0000 0.5125 -0.2500 0.2500
survival/structure-metal-roof -0.2705 0.2737 -0.0000 0.5000 -0.2750 0.2750
survival/structure-metal-wall -0.2677 0.2677 -0.0000 0.5000 -0.2677 -0.1788
survival/structure-metal -0.2677 0.2677 -0.0000 0.5000 -0.2677 0.2677
survival/structure-roof -0.2723 0.2632 0.0000 0.6572 -0.2759 0.2759
survival/structure -0.2500 0.2500 0.0000 0.5000 -0.2500 0.2500
survival/tent-canvas-half -0.2804 0.2804 -0.0000 0.4914 -0.2750 0.2860
survival/tent-canvas -0.2804 0.2804 -0.0000 0.4914 -0.2750 0.2860
survival/tent -0.2804 0.2804 -0.0000 0.4914 -0.2750 0.2860
survival/tool-axe-upgraded -0.0733 0.0733 0.0000 0.2560 -0.0200 0.0200
survival/tool-axe -0.0733 0.0412 0.0000 0.2560 -0.0155 0.0155
survival/tool-hammer-upgraded -0.0580 0.0580 0.0000 0.1846 -0.0258 0.0258
survival/tool-hammer -0.0450 0.0450 0.0000 0.1535 -0.0200 0.0200
survival/tool-hoe-upgraded -0.0693 0.0200 0.0000 0.2400 -0.0455 0.0455
survival/tool-hoe -0.0693 0.0155 0.0000 0.2400 -0.0355 0.0355
survival/tool-pickaxe-upgraded -0.0893 0.0893 0.0000 0.2400 -0.0200 0.0200
survival/tool-pickaxe -0.0893 0.0893 0.0000 0.2400 -0.0193 0.0193
survival/tool-shovel-upgraded -0.0455 0.0455 0.0000 0.2900 -0.0200 0.0255
survival/tool-shovel -0.0355 0.0355 0.0000 0.2900 -0.0155 0.0155
survival/tree-autumn-tall -0.2813 0.2716 0.0000 1.7110 -0.2631 0.2631
survival/tree-autumn-trunk -0.1000 0.1000 0.0000 0.2608 -0.1000 0.1000
survival/tree-autumn -0.2813 0.2716 0.0000 1.4110 -0.2631 0.2631
survival/tree-log-small -0.1247 0.1247 0.0000 0.2771 -0.3250 0.3250
survival/tree-log -0.1221 0.1274 -0.1057 0.1715 -0.5000 0.5000
survival/tree-tall -0.2813 0.2716 0.0000 1.7110 -0.2631 0.2631
survival/tree-trunk -0.1000 0.1000 0.0000 0.2608 -0.1000 0.1000
survival/tree -0.2813 0.2716 0.0000 1.4110 -0.2631 0.2631
survival/workbench-anvil -0.1478 0.1749 0.0000 0.3357 -0.1478 0.1478
survival/workbench-grind -0.1302 0.1302 0.0000 0.2817 -0.1645 0.1645
survival/workbench -0.1478 0.1778 0.0000 0.2866 -0.1478 0.1478
town/balcony-wall-fence 0.4000 0.5000 0.0000 1.0000 -0.5000 0.5000
town/balcony-wall 0.4000 0.5000 0.0000 1.0000 -0.5000 0.5000
town/banner-green 0.3750 0.4250 0.1606 1.0000 -0.2500 0.2500
town/banner-red 0.3750 0.4250 0.1606 1.0000 -0.2500 0.2500
town/blade -0.0555 0.0555 0.0000 2.0000 -0.0555 0.3749
town/cart-high -0.4465 0.4465 -0.0000 0.8605 -0.6450 0.7450
town/cart -0.4465 0.4465 -0.0000 0.5355 -0.6450 0.6950
town/chimney-base 0.0812 0.4250 0.0000 1.0000 -0.2600 0.2600
town/chimney-top 0.2131 0.4650 0.0000 0.6250 -0.1700 0.1700
town/chimney 0.2131 0.4250 0.0000 1.0000 -0.1700 0.1700
town/fence-broken 0.2453 0.5000 -0.0000 0.3800 -0.5000 0.5000
town/fence-curved -0.5000 0.5000 0.0000 0.3800 -0.5000 0.5000
town/fence-gate 0.4250 0.5000 -0.0000 0.3800 -0.5000 0.5000
town/fence 0.4250 0.5000 0.0000 0.3800 -0.5000 0.5000
town/fountain-center -0.5000 0.5000 0.0000 0.1400 -0.5000 0.5000
town/fountain-corner-inner-square -0.5000 0.5000 0.0000 0.2800 -0.5000 0.5000
town/fountain-corner-inner -0.5000 0.5000 0.0000 0.2800 -0.5000 0.5000
town/fountain-corner -0.5000 0.5000 0.0000 0.2800 -0.5000 0.5000
town/fountain-curved -0.5000 0.5000 0.0000 0.2800 -0.5000 0.5000
town/fountain-edge -0.5000 0.5000 0.0000 0.2800 -0.5000 0.5000
town/fountain-round-detail -1.0000 1.0000 -0.0000 0.4800 -1.0000 1.0000
town/fountain-round -1.0000 1.0000 0.0000 0.2800 -1.0000 1.0000
town/fountain-square-detail -1.0000 1.0000 0.0000 0.4800 -1.0000 1.0000
town/fountain-square -1.0000 1.0000 0.0000 0.4552 -1.0000 1.0000
town/hedge-curved -0.5000 0.5000 0.0000 0.2500 -0.5000 0.5000
town/hedge-gate 0.2500 0.5000 0.0000 0.2500 -0.5000 0.5000
town/hedge-large-curved -0.5000 0.5000 0.0000 0.6000 -0.5000 0.5000
town/hedge-large-gate 0.1000 0.5000 0.0000 0.6000 -0.5000 0.5000
town/hedge-large 0.1000 0.5000 0.0000 0.6000 -0.5000 0.5000
town/hedge 0.2500 0.5000 0.0000 0.2500 -0.5000 0.5000
town/lantern -0.1082 0.1082 0.0000 1.5560 -0.1122 0.1122
town/overhang 0.1400 0.4250 0.6700 1.0000 -0.5000 0.5000
town/pillar-stone -0.0800 0.0800 -0.0000 1.0000 -0.0800 0.0800
town/pillar-wood -0.0800 0.0800 -0.0000 1.0000 -0.0800 0.0800
town/planks-half -0.0000 0.5000 0.0000 0.0600 -0.5000 0.5000
town/planks-opening -0.5000 0.5000 0.0000 0.0600 -0.5000 0.5000
town/planks -0.5000 0.5000 0.0000 0.0600 -0.5000 0.5000
town/poles-horizontal 0.4000 0.5000 0.0000 1.0000 -0.5000 0.5000
town/poles 0.4000 0.5000 0.0000 1.0000 -0.5000 0.5000
town/road-bend -1.5000 1.5000 0.0000 0.0500 -1.5000 1.5000
town/road-corner-inner -0.5000 0.5000 0.0000 0.0500 -0.5000 0.5000
town/road-corner -0.5000 0.5000 0.0000 0.0500 -0.5000 0.5000
town/road-curb-end -0.5000 0.5000 0.0000 0.0500 -0.5000 0.5000
town/road-curb -0.5000 0.5000 0.0000 0.0500 -0.5000 0.5000
town/road-edge-slope -0.5000 0.5000 0.0000 0.2500 -0.5000 0.5000
town/road-edge -0.5000 0.5000 0.0000 0.0500 -0.5000 0.5000
town/road-slope -0.5000 0.5000 0.0000 0.2250 -0.5000 0.5000
town/road -0.5000 0.5000 0.0000 0.0250 -0.5000 0.5000
town/rock-large -0.8710 0.7991 0.0000 1.1628 -0.7247 0.8238
town/rock-small -0.5274 0.4709 -0.0000 1.0200 -0.7848 0.5415
town/rock-wide -0.5468 0.5468 0.0000 1.0200 -0.7837 0.7837
town/roof-corner-inner -0.5000 0.5000 0.0000 0.6259 -0.5000 0.5000
town/roof-corner-round -0.5671 0.5000 -0.0224 0.6259 -0.5000 0.5671
town/roof-corner -0.5671 0.5000 -0.0224 0.6259 -0.5000 0.5671
town/roof-flat -0.5000 0.5000 0.0000 0.1259 -0.5000 0.5000
town/roof-gable-detail -0.5500 0.5500 -0.0354 0.6414 -0.6061 0.6061
town/roof-gable-end -0.5354 0.5500 -0.0000 0.5707 -0.5354 0.5354
town/roof-gable-top -0.5000 0.5000 -0.0000 0.3759 -0.5000 0.5000
town/roof-gable -0.5500 0.5500 -0.0000 0.5707 -0.5354 0.5354
town/roof-high-corner-round -0.5707 0.5000 -0.0354 1.1407 -0.5000 0.5707
town/roof-high-corner -0.5707 0.5000 -0.0354 1.1407 -0.5000 0.5707
town/roof-high-cornerinner -0.5000 0.5000 0.0000 1.1407 -0.5000 0.5000
town/roof-high-flat -0.5000 0.5000 0.0000 0.1407 -0.5000 0.5000
town/roof-high-gable-detail -0.6000 0.5000 -0.0894 1.2236 -0.6342 0.6342
town/roof-high-gable-end -0.5675 0.5500 -0.0447 1.1118 -0.5671 0.5671
town/roof-high-gable-top -0.5000 0.5000 0.0000 0.6407 -0.5000 0.5000
town/roof-high-gable -0.5500 0.5500 -0.0447 1.1118 -0.5671 0.5671
town/roof-high-left -0.6414 0.5000 -0.0707 1.1907 -0.5000 0.5000
town/roof-high-point -0.5500 0.5500 0.0000 1.0000 -0.5500 0.5500
town/roof-high-right -0.6414 0.5000 -0.0707 1.1907 -0.5000 0.5000
town/roof-high-window -0.5707 0.5000 -0.0354 1.1407 -0.5000 0.5000
town/roof-high -0.5707 0.5000 -0.0354 1.1407 -0.5000 0.5000
town/roof-left -0.6342 0.5000 -0.0447 0.6759 -0.5000 0.5000
town/roof-point -0.5500 0.5500 0.0000 0.5000 -0.5500 0.5500
town/roof-right -0.6342 0.5000 -0.0447 0.6759 -0.5000 0.5000
town/roof-window -0.5671 0.5000 -0.0224 0.6259 -0.5000 0.5000
town/roof -0.5671 0.5000 -0.0224 0.6259 -0.5000 0.5000
town/stairs-full-corner-inner -0.5000 0.5000 0.0000 0.5000 -0.5000 0.5000
town/stairs-full-corner-outer -0.5200 0.5000 0.0000 0.5000 -0.5200 0.5000
town/stairs-full -0.5200 0.5000 0.0000 0.5000 -0.5000 0.5000
town/stairs-stone-corner -0.5200 0.5000 0.0000 1.0000 -0.5000 0.5000
town/stairs-stone-handrail -0.5200 0.5000 0.0000 1.4450 -0.2500 0.2500
town/stairs-stone-round -0.4310 0.4308 0.0000 1.0000 -0.0554 0.4394
town/stairs-stone -0.5200 0.5000 0.0000 1.0000 -0.2500 0.2500
town/stairs-wide-stone-handrail -0.5200 0.5000 0.0000 1.4450 -0.5000 0.5000
town/stairs-wide-stone -0.5200 0.5000 0.0000 1.0000 -0.5000 0.5000
town/stairs-wide-wood-handrail -0.5200 0.5000 -0.0000 1.4450 -0.5000 0.5000
town/stairs-wide-wood -0.5200 0.5000 -0.0000 1.0000 -0.5000 0.5000
town/stairs-wood-handrail -0.5200 0.5000 -0.0000 1.4450 -0.2500 0.2500
town/stairs-wood -0.5200 0.5000 -0.0000 1.0000 -0.2500 0.2500
town/stall-bench -0.1300 0.1300 0.0000 0.2255 -0.4700 0.4700
town/stall-green -0.5000 0.5000 0.0000 1.2370 -0.5000 0.5000
town/stall-red -0.5000 0.5000 0.0000 1.2370 -0.5000 0.5000
town/stall-stool -0.1300 0.1300 0.0000 0.2255 -0.1300 0.1300
town/stall -0.3250 0.3250 0.0000 0.3655 -0.5000 0.5000
town/tree-crooked -0.5115 0.5115 -0.0000 2.4126 -0.5115 0.5115
town/tree-high-crooked -0.5115 0.5115 0.0000 2.9726 -0.5115 0.5115
town/tree-high-round -0.5093 0.5093 0.0000 2.7506 -0.5093 0.5093
town/tree-high -0.5115 0.5115 0.0000 2.9728 -0.5115 0.5115
town/tree -0.5115 0.5115 0.0000 2.4128 -0.5115 0.5115
town/wall-arch-top-detail 0.3700 0.5300 -0.0000 1.0000 -0.5000 0.5000
town/wall-arch-top 0.4000 0.5000 -0.0000 1.0000 -0.5000 0.5000
town/wall-arch 0.4000 0.5000 -0.0000 1.0000 0.2000 0.5000
town/wall-block-half -0.5000 0.5000 -0.0000 0.5000 -0.5000 0.5000
town/wall-block -0.5000 0.5000 0.0000 1.0000 -0.5000 0.5000
town/wall-broken 0.3976 0.5143 -0.0000 1.0000 -0.5000 0.5000
town/wall-corner-detail 0.3700 0.5300 0.0000 1.0000 0.3700 0.5300
town/wall-corner-diagonal-half -0.0500 0.5000 0.0000 1.0000 -0.5000 0.4750
town/wall-corner-diagonal -0.5000 0.5000 0.0000 1.0000 -0.5000 0.5000
town/wall-corner-edge -0.5000 0.5000 0.0000 1.0000 -0.5000 0.5000
town/wall-corner -0.5000 0.5000 0.0000 1.0000 -0.5000 0.5000
town/wall-curved -0.5000 0.5000 -0.0000 1.0000 -0.5000 0.5000
town/wall-detail-cross 0.4000 0.5000 -0.0000 1.0000 -0.5000 0.5000
town/wall-detail-diagonal 0.4000 0.5000 -0.0000 1.0000 -0.5000 0.5000
town/wall-detail-horizontal 0.4000 0.5000 0.0000 1.0000 -0.5000 0.5000
town/wall-diagonal -0.5000 0.5000 0.0000 1.0000 -0.5000 0.5000
town/wall-door 0.4000 0.5000 0.0000 1.0000 -0.5000 0.5000
town/wall-doorway-base 0.4000 0.5000 -0.0000 1.0000 -0.5000 0.5000
town/wall-doorway-round 0.4000 0.5000 0.0000 1.0000 -0.5000 0.5000
town/wall-doorway-square-wide-curved 0.4000 0.5000 0.0000 1.0000 -0.5000 0.5000
town/wall-doorway-square-wide 0.4000 0.5000 0.0000 1.0000 -0.5000 0.5000
town/wall-doorway-square 0.4000 0.5000 0.0000 1.0000 -0.5000 0.5000
town/wall-half 0.4000 0.5000 0.0000 0.5000 -0.5000 0.5000
town/wall-rounded -0.5000 0.5000 0.0000 1.0000 -0.5000 0.5000
town/wall-side 0.4000 0.5000 -0.0000 1.0000 0.2400 0.5000
town/wall-slope 0.4000 0.5000 0.0000 1.0000 -0.5000 0.5000
town/wall-window-glass 0.4000 0.5000 0.0000 1.0000 -0.5000 0.5000
town/wall-window-round 0.4000 0.5000 0.0000 1.0000 -0.5000 0.5000
town/wall-window-shutters 0.3250 0.5000 0.0000 1.0000 -0.5000 0.5000
town/wall-window-small 0.4000 0.5000 0.0000 1.0000 -0.5000 0.5000
town/wall-window-stone 0.3750 0.5250 0.0000 1.0000 -0.5000 0.5000
town/wall-wood-arch-top-detail 0.3700 0.5300 -0.0000 1.0000 -0.5000 0.5000
town/wall-wood-arch-top 0.4000 0.5000 -0.0000 1.0000 -0.5000 0.5000
town/wall-wood-arch 0.4000 0.5000 -0.0000 1.0000 0.2000 0.5000
town/wall-wood-block-half -0.5000 0.5000 -0.0000 0.5000 -0.5000 0.5000
town/wall-wood-block -0.5000 0.5000 0.0000 1.0000 -0.5000 0.5000
town/wall-wood-broken 0.3967 0.5096 -0.0000 1.0000 -0.5000 0.5000
town/wall-wood-corner-diagonal-half -0.0500 0.5000 0.0000 1.0000 -0.5000 0.4750
town/wall-wood-corner-diagonal -0.5000 0.5000 0.0000 1.0000 -0.5000 0.5000
town/wall-wood-corner-edge -0.5000 0.5000 0.0000 1.0000 -0.5000 0.5000
town/wall-wood-corner -0.5000 0.5000 0.0000 1.0000 -0.5000 0.5000
town/wall-wood-curved -0.5000 0.5000 -0.0000 1.0000 -0.5000 0.5000
town/wall-wood-detail-cross 0.4000 0.5000 -0.0000 1.0000 -0.5000 0.5000
town/wall-wood-detail-diagonal 0.4000 0.5000 -0.0000 1.0000 -0.5000 0.5000
town/wall-wood-detail-horizontal 0.4000 0.5000 0.0000 1.0000 -0.5000 0.5000
town/wall-wood-diagonal -0.5000 0.5000 0.0000 1.0000 -0.5000 0.5000
town/wall-wood-door 0.4000 0.5000 0.0000 1.0000 -0.5000 0.5000
town/wall-wood-doorway-base 0.4000 0.5000 -0.0000 1.0000 -0.5000 0.5000
town/wall-wood-doorway-round 0.4000 0.5000 0.0000 1.0000 -0.5000 0.5000
town/wall-wood-doorway-square-wide-curved 0.4000 0.5000 0.0000 1.0000 -0.5000 0.5000
town/wall-wood-doorway-square-wide 0.4000 0.5000 0.0000 1.0000 -0.5000 0.5000
town/wall-wood-doorway-square 0.4000 0.5000 0.0000 1.0000 -0.5000 0.5000
town/wall-wood-half 0.4000 0.5000 0.0000 0.5000 -0.5000 0.5000
town/wall-wood-rounded -0.5000 0.5000 0.0000 1.0000 -0.5000 0.5000
town/wall-wood-side 0.4000 0.5000 -0.0000 1.0000 0.2400 0.5000
town/wall-wood-slope 0.4000 0.5000 0.0000 1.0000 -0.5000 0.5000
town/wall-wood-window-glass 0.4000 0.5000 0.0000 1.0000 -0.5000 0.5000
town/wall-wood-window-round 0.3500 0.5500 0.0000 1.0000 -0.5000 0.5000
town/wall-wood-window-shutters 0.4000 0.5000 0.0000 1.0000 -0.5000 0.5000
town/wall-wood-window-small 0.3500 0.5500 0.0000 1.0000 -0.5000 0.5000
town/wall-wood-window-stone 0.3750 0.5250 0.0000 1.0000 -0.5000 0.5000
town/wall-wood 0.4000 0.5000 0.0000 1.0000 -0.5000 0.5000
town/wall 0.4000 0.5000 0.0000 1.0000 -0.5000 0.5000
town/watermill-wide -0.5250 0.5250 -0.8995 0.8995 -0.8995 0.8995
town/watermill -0.4250 0.4250 -0.8995 0.8995 -0.8995 0.8995
town/wheel 0.1989 0.4373 0.0000 0.4833 -0.2339 0.2339
town/windmill -0.2355 0.2355 -1.5566 1.5566 -1.5566 1.5566
vehicles/delivery -0.7500 0.7500 0.0000 1.6500 -1.6500 1.6000
vehicles/sedan -0.7500 0.7500 0.0000 1.3000 -1.3000 1.2500
vehicles/suv -0.7500 0.7500 0.0000 1.3000 -1.3500 1.3500
vehicles/tractor-shovel -0.8303 0.8303 0.0000 1.5120 -1.2350 1.2350
vehicles/tractor -0.6710 0.6710 0.0000 1.6021 -1.1008 1.1008
vehicles/truck-flat -0.7500 0.7500 0.0000 1.3000 -1.3726 1.3726
vehicles/truck -0.7500 0.7500 0.0000 1.3000 -1.5000 1.4500
vehicles/van -0.7500 0.7500 0.0000 1.3500 -1.4000 1.3500
vehicles/wheel-default -0.2000 0.2000 -0.3000 0.3000 -0.3000 0.3000
vehicles/wheel-tractor-back -0.2688 0.2688 -0.4376 0.4376 -0.4376 0.4376
vehicles/wheel-tractor-front -0.1846 0.1846 -0.2693 0.2693 -0.2693 0.2693
vehicles/wheel-truck -0.1750 0.1750 -0.3000 0.3000 -0.3000 0.3000
water/boat-fishing-small -0.8925 0.8925 0.0000 2.6000 -1.9350 1.9350
water/boat-house-a -1.3388 1.3388 0.0000 2.1725 -2.3220 2.3220
water/boat-row-large -1.3743 1.3743 -0.0000 0.8477 -1.4261 1.4261
water/boat-row-small -1.3743 1.3743 -0.0000 0.8477 -1.1861 1.1861
water/boat-sail-a -0.8925 0.8925 0.0000 4.7391 -1.7850 1.9850
water/buoy-flag -0.4641 0.4641 -0.3000 2.4175 -0.8252 0.4641
water/buoy -0.4641 0.4641 -0.3000 1.5441 -0.4641 0.4641
water/ramp-wide -2.5720 2.5720 0.0000 1.1369 -1.4135 1.4006
water/ramp -1.3645 1.3645 0.0000 1.1369 -1.4135 1.4006
works/door-wide-closed -0.9000 0.9000 0.0000 1.6000 0.4000 0.4000
works/hopper-high-round -0.5591 0.5591 0.0000 1.5000 -0.5591 0.5591
works/hopper-high-square -0.5586 0.5586 0.0000 1.5000 -0.5586 0.5586
works/hopper-round -0.5591 0.5591 0.0000 1.0000 -0.5591 0.5591
works/hopper-square -0.5586 0.5586 0.0000 1.0000 -0.5586 0.5586
works/machine-bed -0.6000 1.7500 -0.0000 1.2985 -0.7500 1.6000
works/machine-fortified -0.6000 0.6000 -0.0000 1.3505 -0.8000 0.8000
works/machine-window -0.6000 0.6000 -0.0000 1.2897 -0.7500 0.7500
works/machine -0.6000 0.6000 -0.0000 1.2998 -0.7500 0.7500
works/pipe-large-bend -0.9000 1.0000 -0.0002 1.0000 -1.4000 0.5000
works/pipe-large-valve -0.5000 0.5000 -0.0000 1.0000 -0.5156 0.5000
works/pipe-large -0.5000 0.5000 -0.0000 1.0000 -0.5000 0.5000
works/structure-doorway-wide -1.0000 1.0000 0.0000 3.0000 -0.5000 1.5000
works/structure-doorway -0.5000 0.5000 0.0000 3.0000 -0.5000 1.5000
works/structure-high -0.1500 0.1500 -0.0000 1.5000 -0.5500 0.5500
works/structure-medium -0.1500 0.1500 -0.0000 1.0000 -0.5500 0.5500
works/structure-short -0.1500 0.1500 0.0000 0.5000 -0.5500 0.5500
works/structure-tall -0.1500 0.1500 0.0000 2.0000 -0.5500 0.5500
works/structure-wall -0.5000 0.5000 0.0000 3.0000 -0.5000 1.5000
works/structure-window-wide -1.0000 1.0000 0.0000 3.0000 -0.5000 1.5000
works/structure-window -0.5000 0.5000 0.0000 3.0000 -0.5000 1.5000
works/top-large -1.0000 1.0000 0.0000 0.0000 -1.0000 1.0000
works/top -0.5000 0.5000 0.0000 0.0000 -0.5000 0.5000
yard/bench -0.4036 0.4036 0.0000 0.5260 -0.2276 0.2276
yard/debris-wood -0.2293 0.2293 0.0000 0.1000 -0.2514 0.2528
yard/fence-damaged -0.5000 0.5000 0.0000 0.6201 -0.1107 0.2014
yard/fence-gate -0.5000 0.5000 0.0000 0.6201 -0.1020 0.1020
yard/fence -0.5000 0.5000 0.0000 0.6201 -0.0920 0.0920
yard/hay-bale-bundled -0.3033 0.3033 0.0000 0.3798 -0.2156 0.2156
yard/hay-bale -0.3033 0.3033 0.0129 0.3670 -0.2010 0.2010
yard/iron-fence-bar -0.0597 0.0597 0.0000 0.6689 -0.0517 0.0517
yard/iron-fence-border-column -0.5000 0.5000 0.0000 0.8789 -0.4358 -0.2142
yard/iron-fence-border-gate -0.5000 0.5000 0.0000 0.7600 -0.4358 -0.2142
yard/iron-fence-border -0.5000 0.5000 0.0000 0.8789 -0.4000 -0.2500
yard/iron-fence-curve -0.3800 0.5000 -0.0000 0.8789 -0.3800 0.5000
yard/iron-fence -0.5000 0.5000 0.0000 0.8789 -0.3800 -0.2700
yard/lightpost-double -0.1044 0.1044 -0.0000 1.2666 -0.3633 0.3633
yard/lightpost-single -0.1044 0.1044 -0.0000 1.2666 -0.1016 0.3633
yard/pine-crooked -0.5711 0.6069 -0.1000 2.0081 -0.6673 0.6673
yard/pine-fall-crooked -0.5711 0.6069 -0.1000 2.0081 -0.6673 0.6673
yard/pine-fall -0.5890 0.5890 -0.1000 2.2025 -0.6673 0.6673
yard/pine -0.5890 0.5890 -0.1000 2.2025 -0.6673 0.6673
yard/pumpkin-tall -0.1628 0.1628 0.0000 0.3597 -0.1368 0.1888
yard/pumpkin -0.1888 0.1888 0.0000 0.3211 -0.1888 0.1888
yard/rocks-tall -0.5104 0.5227 -0.0000 0.5876 -0.5648 0.4553
yard/rocks -0.4353 0.6406 0.0000 0.3775 -0.4310 0.5334
yard/shovel -0.0960 0.0960 0.0000 0.6122 -0.0477 0.0477
yard/stone-wall-column -0.5000 0.5000 0.0000 0.8500 -0.5750 -0.2250
yard/stone-wall-curve -0.5000 0.5000 0.0000 0.7250 -0.5000 0.5000
yard/stone-wall -0.5000 0.5000 0.0000 0.7250 -0.5000 -0.3000
yard/trunk-long -0.2697 0.2697 0.0000 1.0000 -0.2697 0.2712
"""
}
