#!/usr/bin/env python3
"""Measure every vendored mesh and generate `ModelMetrics.swift`.

A plan says "house, 12 x 10 metres". A mesh says nothing at all about metres —
it is some number of model units across, decided by whoever modelled it. To put
the two together the scene builder has to know how big each mesh actually is,
and it has to know it *here*, on Linux, where the scene builder is tested and
where the app itself cannot be built.

So the bounding boxes are measured from the OBJ files and baked into a
generated Swift table. Every size in the scene is then computed, not guessed,
and `SceneBuilderTests` can check that a building really does come out 12
metres wide without anyone opening Xcode.

    python3 scripts/build_model_metrics.py            # regenerate
    python3 scripts/build_model_metrics.py --check    # fail if out of date
"""

import argparse
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
MODELS = ROOT / "Homestead" / "Homestead" / "Models3D"
OUTPUT = ROOT / "swift" / "Sources" / "HomesteadCore" / "ModelMetrics.swift"

HEADER = '''//  Generated by scripts/build_model_metrics.py — do not edit by hand.
//
//  The bounding box of every vendored mesh, in its own model units, measured
//  from the OBJ files. See the script for why this is generated rather than
//  read at runtime: the scene builder needs real sizes on a platform that
//  cannot open a mesh, let alone render one.
//
//  Axes are the meshes' own — Kenney models are Y-up, like SceneKit. The
//  engine is Z-up, and `SceneNode` is where the two are reconciled, once.

import Foundation

/// How big one mesh is, and where it sits relative to its own origin.
public struct ModelBounds: Equatable, Sendable {
    public let minX: Double, maxX: Double
    public let minY: Double, maxY: Double
    public let minZ: Double, maxZ: Double

    public init(minX: Double, maxX: Double, minY: Double, maxY: Double, minZ: Double, maxZ: Double) {
        self.minX = minX; self.maxX = maxX
        self.minY = minY; self.maxY = maxY
        self.minZ = minZ; self.maxZ = maxZ
    }

    /// Extent along each of the mesh's own axes.
    public var width: Double { maxX - minX }
    public var height: Double { maxY - minY }
    public var depth: Double { maxZ - minZ }

    /// The largest horizontal extent — what a mesh is "about" that big.
    public var span: Double { max(width, depth) }

    /// The centre of the box, which is rarely the origin.
    public var centreX: Double { (minX + maxX) / 2 }
    public var centreZ: Double { (minZ + maxZ) / 2 }

    /// How far the mesh's own origin sits above its lowest point. Most of
    /// these kits model with the origin on the ground, but not all of them,
    /// and one that does not will float or sink.
    public var baseOffset: Double { -minY }
}

public enum ModelMetrics {
    /// Every vendored mesh, by `kit/name`.
    public static let all: [String: ModelBounds] = parse(table)

    public static subscript(_ name: String) -> ModelBounds? { all[name] }

    public static var names: [String] { all.keys.sorted() }

    /// One line per mesh: `name minX maxX minY maxY minZ maxZ`.
    ///
    /// A string rather than a dictionary literal on purpose. Swift type-checks
    /// a 380-entry literal of six-field structs slowly enough to notice, and
    /// this parses in microseconds, once.
    private static func parse(_ table: String) -> [String: ModelBounds] {
        var result: [String: ModelBounds] = [:]
        result.reserveCapacity(400)
        for line in table.split(separator: "\\n") {
            let field = line.split(separator: " ")
            guard field.count == 7, let minX = Double(field[1]), let maxX = Double(field[2]),
                  let minY = Double(field[3]), let maxY = Double(field[4]),
                  let minZ = Double(field[5]), let maxZ = Double(field[6]) else { continue }
            result[String(field[0])] = ModelBounds(
                minX: minX, maxX: maxX, minY: minY, maxY: maxY, minZ: minZ, maxZ: maxZ
            )
        }
        return result
    }

    private static let table = """
'''


def measure(path):
    lo = [float("inf")] * 3
    hi = [float("-inf")] * 3
    with open(path) as handle:
        for line in handle:
            if not line.startswith("v "):
                continue
            parts = line.split()
            for axis in range(3):
                value = float(parts[axis + 1])
                lo[axis] = min(lo[axis], value)
                hi[axis] = max(hi[axis], value)
    if lo[0] == float("inf"):
        return None
    return lo, hi


def generate():
    rows = []
    for obj in sorted(MODELS.glob("*/*.obj")):
        box = measure(obj)
        if box is None:
            print("warning: %s has no vertices" % obj.name, file=sys.stderr)
            continue
        lo, hi = box
        name = "%s/%s" % (obj.parent.name, obj.stem)
        rows.append("%s %s" % (name, " ".join("%.4f" % v for v in (lo[0], hi[0], lo[1], hi[1], lo[2], hi[2]))))
    return HEADER + "\n".join(rows) + '\n"""\n}\n'


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    generated = generate()
    if args.check:
        if not OUTPUT.exists():
            print("error: %s has never been generated" % OUTPUT.name, file=sys.stderr)
            return 1
        if OUTPUT.read_text() != generated:
            print(
                "error: %s is out of date — run scripts/build_model_metrics.py" % OUTPUT.name,
                file=sys.stderr,
            )
            return 1
        print("model metrics up to date (%d meshes)" % len(list(MODELS.glob("*/*.obj"))))
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generated)
    print("wrote %s (%d meshes)" % (OUTPUT.relative_to(ROOT), len(list(MODELS.glob("*/*.obj")))))
    return 0


if __name__ == "__main__":
    sys.exit(main())
