#!/usr/bin/env python3
"""Measure every vendored mesh and generate `ModelMetrics.swift`.

A plan says "house, 12 x 10 metres". A mesh says nothing at all about metres —
it is some number of model units across, decided by whoever modelled it. To put
the two together the scene builder has to know how big each mesh actually is,
and it has to know it *here*, on Linux, where the scene builder is tested and
where the app itself cannot be built.

So the bounding boxes are measured from the OBJ files and baked into a
generated Swift table. Every size in the scene is then computed, not guessed,
and `SceneBuilderTests` can check that a building really does come out 12
metres wide without anyone opening Xcode.

    python3 scripts/build_model_metrics.py            # regenerate
    python3 scripts/build_model_metrics.py --check    # fail if out of date
"""

import argparse
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
MODELS = ROOT / "Homestead" / "Homestead" / "Models3D"
OUTPUT = ROOT / "swift" / "Sources" / "HomesteadCore" / "ModelMetrics.swift"

HEADER = '''//  Generated by scripts/build_model_metrics.py — do not edit by hand.
//
//  The bounding box of every vendored mesh, in its own model units, measured
//  from the OBJ files. See the script for why this is generated rather than
//  read at runtime: the scene builder needs real sizes on a platform that
//  cannot open a mesh, let alone render one.
//
//  Axes are the meshes' own — Kenney models are Y-up, like SceneKit. The
//  engine is Z-up, and `SceneNode` is where the two are reconciled, once.

import Foundation

/// How big one mesh is, and where it sits relative to its own origin.
public struct ModelBounds: Equatable, Sendable {
    public let minX: Double, maxX: Double
    public let minY: Double, maxY: Double
    public let minZ: Double, maxZ: Double

    public init(
        minX: Double, maxX: Double, minY: Double, maxY: Double, minZ: Double, maxZ: Double,
        surface: [Double] = []
    ) {
        self.minX = minX; self.maxX = maxX
        self.minY = minY; self.maxY = maxY
        self.minZ = minZ; self.maxZ = maxZ
        self.surface = surface
    }

    /// Extent along each of the mesh's own axes.
    public var width: Double { maxX - minX }
    public var height: Double { maxY - minY }
    public var depth: Double { maxZ - minZ }

    /// The largest horizontal extent — what a mesh is "about" that big.
    public var span: Double { max(width, depth) }

    /// The centre of the box, which is rarely the origin.
    public var centreX: Double { (minX + maxX) / 2 }
    public var centreZ: Double { (minZ + maxZ) / 2 }

    /// How far the mesh's own origin sits above its lowest point. Most of
    /// these kits model with the origin on the ground, but not all of them,
    /// and one that does not will float or sink.
    public var baseOffset: Double { -minY }

    /// The mesh's upper surface, as a 6 by 6 grid of heights over its own
    /// footprint, each a fraction of its total height. Row-major, X across,
    /// Z down; zero where the mesh has nothing above that spot.
    ///
    /// A bounding box says a house is nine metres tall. It does not say what
    /// is nine metres tall *where* — and anything that has to stand on top of
    /// something needs exactly that. A cross-section profile was tried first
    /// and cannot answer it: at a third of a house's height the cross-section
    /// is nearly full, but that is the first floor, and a solar array seated
    /// there is inside the building. This says how high the roof is over each
    /// patch of ground, which is the question.
    public let surface: [Double]

    /// How high the mesh stands over the part of its footprint from
    /// `(x0, z0)` to `(x1, z1)`, each given as a fraction of its own extent.
    /// The maximum, not the mean: something laid on a roof has to clear the
    /// ridge under it, not the average of the ridge and the eaves.
    public func top(from x0: Double, _ z0: Double, to x1: Double, _ z1: Double) -> Double? {
        guard !surface.isEmpty else { return nil }
        let side = Int(Double(surface.count).squareRoot().rounded())
        guard side * side == surface.count, side > 0 else { return nil }
        func cell(_ value: Double) -> Int { min(side - 1, max(0, Int(value * Double(side)))) }
        var highest = 0.0
        for column in cell(min(x0, x1))...cell(max(x0, x1)) {
            for row in cell(min(z0, z1))...cell(max(z0, z1)) {
                highest = max(highest, surface[row * side + column])
            }
        }
        return highest
    }
}

public enum ModelMetrics {
    /// Every vendored mesh, by `kit/name`.
    public static let all: [String: ModelBounds] = parse(table)

    public static subscript(_ name: String) -> ModelBounds? { all[name] }

    public static var names: [String] { all.keys.sorted() }

    /// One line per mesh: `name minX maxX minY maxY minZ maxZ` and then a
    /// 6 by 6 grid of surface heights, row-major.
    ///
    /// A string rather than a dictionary literal on purpose. Swift type-checks
    /// a 380-entry literal of six-field structs slowly enough to notice, and
    /// this parses in microseconds, once.
    private static func parse(_ table: String) -> [String: ModelBounds] {
        var result: [String: ModelBounds] = [:]
        result.reserveCapacity(400)
        for line in table.split(separator: "\\n") {
            let field = line.split(separator: " ")
            guard field.count >= 7, let minX = Double(field[1]), let maxX = Double(field[2]),
                  let minY = Double(field[3]), let maxY = Double(field[4]),
                  let minZ = Double(field[5]), let maxZ = Double(field[6]) else { continue }
            result[String(field[0])] = ModelBounds(
                minX: minX, maxX: maxX, minY: minY, maxY: maxY, minZ: minZ, maxZ: maxZ,
                surface: field.dropFirst(7).compactMap { Double($0) }
            )
        }
        return result
    }

    private static let table = """
'''


GRID = 6


def measure(path):
    """The bounding box, and how high the mesh stands over each patch of its
    own footprint.

    Triangles are rasterised into a plan grid and each cell keeps the highest
    point of any triangle over it. That is what "can something stand here"
    means, and it is the third attempt at the question: vertex spread and
    cross-section profiles both answer "how much of the mesh is at this
    height", which is not the same thing and put a solar array first above
    the ridge and then inside the first floor.
    """
    points = []
    faces = []
    lo = [float("inf")] * 3
    hi = [float("-inf")] * 3
    with open(path) as handle:
        for line in handle:
            if line.startswith("v "):
                parts = line.split()
                p = tuple(float(parts[axis + 1]) for axis in range(3))
                points.append(p)
                for axis in range(3):
                    lo[axis] = min(lo[axis], p[axis])
                    hi[axis] = max(hi[axis], p[axis])
            elif line.startswith("f "):
                corners = [int(token.split("/")[0]) - 1 for token in line.split()[1:]]
                for i in range(1, len(corners) - 1):
                    faces.append((corners[0], corners[i], corners[i + 1]))
    if not points:
        return None

    height = max(hi[1] - lo[1], 1e-9)
    spanX = max(hi[0] - lo[0], 1e-9)
    spanZ = max(hi[2] - lo[2], 1e-9)
    tops = [0.0] * (GRID * GRID)
    for a, b, c in faces:
        try:
            tri = (points[a], points[b], points[c])
        except IndexError:
            continue
        xs = [(p[0] - lo[0]) / spanX * GRID for p in tri]
        zs = [(p[2] - lo[2]) / spanZ * GRID for p in tri]
        ys = [(p[1] - lo[1]) / height for p in tri]
        area = (xs[1] - xs[0]) * (zs[2] - zs[0]) - (xs[2] - xs[0]) * (zs[1] - zs[0])

        def record(gx, gz, value):
            index = gz * GRID + gx
            if value > tops[index]:
                tops[index] = value

        for gx in range(max(0, int(min(xs))), min(GRID, int(max(xs)) + 1)):
            for gz in range(max(0, int(min(zs))), min(GRID, int(max(zs)) + 1)):
                px, pz = gx + 0.5, gz + 0.5
                if abs(area) < 1e-12:
                    continue
                # Barycentric, so a sloping plane records the height it
                # actually has over each cell. Taking the triangle's peak for
                # its whole bounding box instead made every long low roof
                # read as full height everywhere — a building with no shape.
                w0 = ((px - xs[1]) * (zs[2] - zs[1]) - (xs[2] - xs[1]) * (pz - zs[1])) / area
                w1 = ((px - xs[2]) * (zs[0] - zs[2]) - (xs[0] - xs[2]) * (pz - zs[2])) / area
                w2 = 1 - w0 - w1
                if w0 >= -1e-9 and w1 >= -1e-9 and w2 >= -1e-9:
                    record(gx, gz, w0 * ys[0] + w1 * ys[1] + w2 * ys[2])

        # And the edges, at the height they have there. A wall is edge-on from
        # above and covers no cell centre at all, so without this the eaves
        # come out as holes in the map.
        for i in range(3):
            j = (i + 1) % 3
            steps = int(max(abs(xs[j] - xs[i]), abs(zs[j] - zs[i])) * 2) + 1
            for step in range(steps + 1):
                t = step / steps
                cx, cz = int(xs[i] + (xs[j] - xs[i]) * t), int(zs[i] + (zs[j] - zs[i]) * t)
                if 0 <= cx < GRID and 0 <= cz < GRID:
                    record(cx, cz, ys[i] + (ys[j] - ys[i]) * t)
    return lo, hi, tops


def generate():
    rows = []
    for obj in sorted(MODELS.glob("*.obj")):
        box = measure(obj)
        if box is None:
            print("warning: %s has no vertices" % obj.name, file=sys.stderr)
            continue
        lo, hi, surface = box
        # Vendored flat as `kit_name.obj`; the table is keyed by `kit/name`.
        name = obj.stem.replace("_", "/", 1)
        rows.append("%s %s %s" % (
            name,
            " ".join("%.4f" % v for v in (lo[0], hi[0], lo[1], hi[1], lo[2], hi[2])),
            " ".join("%.3f" % v for v in surface),
        ))
    return HEADER + "\n".join(rows) + '\n"""\n}\n'


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    generated = generate()
    if args.check:
        if not OUTPUT.exists():
            print("error: %s has never been generated" % OUTPUT.name, file=sys.stderr)
            return 1
        if OUTPUT.read_text() != generated:
            print(
                "error: %s is out of date — run scripts/build_model_metrics.py" % OUTPUT.name,
                file=sys.stderr,
            )
            return 1
        print("model metrics up to date (%d meshes)" % len(list(MODELS.glob("*.obj"))))
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generated)
    print("wrote %s (%d meshes)" % (OUTPUT.relative_to(ROOT), len(list(MODELS.glob("*.obj")))))
    return 0


if __name__ == "__main__":
    sys.exit(main())
