import Testing
import Foundation
@testable import HomesteadEngine

/// `hypot` is IEEE-754 "correctly rounded to within about 1 ULP," not
/// "bit-identical across implementations" — glibc's `hypot` (this port, on
/// Linux) and V8's `Math.hypot` (the reference fixtures, generated by Node)
/// are both valid and disagree in the last bit for a small fraction of
/// inputs: measured directly, 3 of 517 point-pairs across every path in the
/// 48 golden fixtures. `polylineLength` sums several such calls per path, so
/// a single-ULP disagreement in one segment survives into the summed
/// length, and from there into a cost/quantity total. Every other exact-
/// equality fixture test in this suite never hits this because it either
/// doesn't sum many `distance()` calls together (most call sites) or only
/// ever compares a distance against a threshold rather than displaying the
/// value — this is the first place a `distance()`-derived number is both
/// summed repeatedly and asserted for exact equality. Relative tolerance
/// here isn't a loosened bar for the port; it's the actual, irreducible
/// precision `hypot` promises, applied to the one output shape that
/// exposes it.
private let costTolerance = 1e-9

private func approximately(_ a: Double, _ b: Double, relativeTo scale: Double = 1) -> Bool {
    abs(a - b) <= costTolerance * max(1, abs(scale))
}

private func expectApproximatelyEqual(_ actual: CostEstimate, _ expected: CostEstimate, _ comment: Comment) {
    #expect(actual.region == expected.region, comment)
    #expect(approximately(actual.landAreaM2, expected.landAreaM2), comment)
    #expect(approximately(actual.landCostUsd, expected.landCostUsd), comment)
    #expect(actual.rows.count == expected.rows.count, comment)
    for (a, e) in zip(actual.rows, expected.rows) {
        #expect(a.label == e.label && a.category == e.category && a.special == e.special, comment)
        #expect(approximately(a.installUsd, e.installUsd), comment)
        #expect(approximately(a.annualUsd, e.annualUsd), comment)
    }
    #expect(approximately(actual.constructionTotalUsd, expected.constructionTotalUsd), comment)
    #expect(approximately(actual.annualMaintenanceTotalUsd, expected.annualMaintenanceTotalUsd), comment)
    #expect(approximately(actual.totalUpfrontUsd, expected.totalUpfrontUsd), comment)
}

private func expectApproximatelyEqual(_ actual: MaterialsTakeoff, _ expected: MaterialsTakeoff, _ comment: Comment) {
    #expect(actual.fences.count == expected.fences.count, comment)
    for (a, e) in zip(actual.fences, expected.fences) {
        #expect(a.fenceType == e.fenceType, comment)
        #expect(approximately(a.lengthM, e.lengthM), comment)
    }
    #expect(approximately(actual.totalFenceLengthM, expected.totalFenceLengthM), comment)
    #expect(actual.paths.count == expected.paths.count, comment)
    for (a, e) in zip(actual.paths, expected.paths) {
        #expect(a.group == e.group, comment)
        #expect(approximately(a.lengthM, e.lengthM), comment)
        #expect(approximately(a.widthM, e.widthM), comment)
        #expect(approximately(a.areaM2, e.areaM2), comment)
    }
    #expect(approximately(actual.totalPavedAreaM2, expected.totalPavedAreaM2), comment)
    #expect(approximately(actual.totalGravelAreaM2, expected.totalGravelAreaM2), comment)
    #expect(actual.structures.count == expected.structures.count, comment)
    for (a, e) in zip(actual.structures, expected.structures) {
        #expect(a.typeId == e.typeId && a.label == e.label, comment)
        #expect(approximately(a.widthM, e.widthM))
        #expect(approximately(a.heightM, e.heightM))
        #expect(approximately(a.areaM2, e.areaM2))
    }
}

private struct CostFixture: Decodable {
    let fixture: String
    let regionId: String
    let region: CostRegion
    let output: CostEstimate
}

private struct MaterialsFixture: Decodable {
    let fixture: String
    let output: MaterialsTakeoff
}

/// `computeCostEstimate`/`computeMaterialsTakeoff` are pure functions of a
/// layout's objects/paths/fences (plus, for costs, totalAreaM2 and a
/// region) — no isolated fixture needed, since the objects/paths/fences
/// they read are exactly what `GenerateTests` already verified in each of
/// the 48 golden fixtures. `costs.json`/`materials.json` reference those
/// fixtures by name rather than duplicating their content.
@Test func costEstimateMatchesEveryFixtureAcrossEveryRegion() throws {
    let data = try Data(contentsOf: Fixtures.directory.appendingPathComponent("costs.json"))
    let fixtures = try JSONDecoder().decode([CostFixture].self, from: data)
    #expect(fixtures.count == 48 * 3)

    var cache: [String: GoldenFixture] = [:]
    for fixture in fixtures {
        let golden = try cache[fixture.fixture] ?? Fixtures.golden(fixture.fixture)
        cache[fixture.fixture] = golden

        let actual = Costs.estimate(
            objects: golden.output.objects,
            paths: golden.output.paths,
            fences: golden.output.fences,
            totalAreaM2: golden.output.analytics.totalAreaM2,
            region: fixture.region
        )
        expectApproximatelyEqual(actual, fixture.output, Comment(rawValue: "\(fixture.fixture) / \(fixture.regionId)"))
    }
}

@Test func materialsTakeoffMatchesEveryFixture() throws {
    let data = try Data(contentsOf: Fixtures.directory.appendingPathComponent("materials.json"))
    let fixtures = try JSONDecoder().decode([MaterialsFixture].self, from: data)
    #expect(fixtures.count == 48)

    for fixture in fixtures {
        let golden = try Fixtures.golden(fixture.fixture)
        let actual = Materials.takeoff(objects: golden.output.objects, paths: golden.output.paths, fences: golden.output.fences)
        expectApproximatelyEqual(actual, fixture.output, Comment(rawValue: fixture.fixture))
    }
}
